apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.application.name }}
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.replicas.count }}
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.application.name }}
    spec:
      containers:
      - image: nginx:{{ .Values.image.tag }}
        name: nginx
        resources: {}
status: {}
