apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{.Release.Name}}
  name: {{.Release.Name}}-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.application.port }}
  selector:
    app: {{.Release.Name}}
status:
  loadBalancer: {}
