apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: web
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service
spec:
  selector:
    matchLabels:
      app: web
  serviceName: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: container-name
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: pvc-name
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: pvc-name
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
